SELECT [Customer ID]
      ,[Name]
      ,[Email]
      ,[Telephone]
      ,[City]
      ,[Country]
      ,[Gender]
      ,[Date Of Birth]
      ,[Job Title]
  FROM [Skippy].[dbo].[customers]
